---
# tasks file for kvm_provision
- name: Ensure requirements in place
  become: yes
  package:
    name:
      - libguestfs-tools
      - python3-libvirt
    state: present

- name: Get VMs list
  community.libvirt.virt:
    command: list_vms
  register: existing_vms
  changed_when: false

- block:
  - name: Create VM if not exists
    community.libvirt.virt:
      command: define
      xml: "{{ lookup('template', 'vm-template.xml.j2') }}"

  - name: Ensure VM is started
    community.libvirt.virt:
      name: "{{ vm_name }}"
      state: running
    register: vm_start_results
    until: "vm_start_results is success"
    retries: 15
    delay: 2
  when: "vm_name not in existing_vms.list_vms"